const SUPABASE_URL="https://fqihuqmxbygpafpyuvfs.supabase.co",KEY="sb_publishable__-tCChM7wpWOm0S_FuXlmw_3TilDyf-",db=supabase.createClient(SUPABASE_URL,KEY);
const $=s=>document.querySelector(s),esc=s=>String(s||"").replace(/[&<>"']/g,x=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[x]));
const cols=[["inbox","Входящие","#94a3b8"],["progress","В работе","#0ea5e9"],["waiting","На контроле","#f59e0b"],["done","Сделано","#10b981"]];let tasks=[],comments=[],current=null,user=null,registerMode=false;
const fmt=x=>new Date(x).toLocaleString("ru-RU",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"});
function showApp(sessionUser){user=sessionUser||null;$("#auth-view").hidden=!!user;$("#app-view").hidden=!user;if(user)load()}
function authNotice(message,isError=false){$("#auth-notice").textContent=message;$("#auth-notice").classList.toggle("auth-error",isError)}
function setAuthMode(){ $("#auth-submit").textContent=registerMode?"Зарегистрироваться":"Войти";$("#auth-switch").textContent=registerMode?"У меня уже есть учётная запись":"Создать учётную запись";$("#auth-password").autocomplete=registerMode?"new-password":"current-password";authNotice("") }
async function load(){if(!user)return;$("#load-error").hidden=true;let a=await db.from("tasks").select("*").eq("user_id",user.id).order("updated_at",{ascending:false}),b=await db.from("task_comments").select("*").eq("user_id",user.id).order("created_at",{ascending:false});if(a.error||b.error){$("#load-error").hidden=false;$("#load-error").textContent="Не удалось загрузить задачи. Проверьте настройку доступа к базе.";return}tasks=a.data||[];comments=b.data||[];render()}
function render(){let q=$("#search").value.toLowerCase(),cat=$("#category-filter").value,st=$("#status-filter").value,shown=tasks.filter(t=>(!cat||t.category===cat)&&(!st||t.status===st)&&((t.title+" "+t.description+" "+(t.tags||[]).join(" ")).toLowerCase().includes(q)));$("#board").innerHTML=cols.map(c=>{let list=shown.filter(t=>t.status===c[0]);return '<section class="column"><div class="column-head"><span><i style="background:'+c[2]+'"></i>'+c[1]+'<em class="count">'+list.length+'</em></span><button class="add-small" data-new="'+c[0]+'">＋</button></div><div class="cards">'+list.map(card).join("")+(!list.length?'<button class="card" data-new="'+c[0]+'" style="color:#8994a6;text-align:center;border-style:dashed">Добавить задачу</button>':"")+'</div></section>'}).join("");document.querySelectorAll("[data-task]").forEach(x=>x.onclick=()=>openTask(x.dataset.task));document.querySelectorAll("[data-new]").forEach(x=>x.onclick=()=>openTask(null,x.dataset.new))}
function card(t){let n=comments.filter(c=>c.task_id===t.id).length,due=t.due_date?new Date(t.due_date+"T00:00:00").toLocaleDateString("ru-RU",{day:"2-digit",month:"short"}):"",late=t.due_date&&new Date(t.due_date+"T00:00:00")<new Date(new Date().toDateString());return '<button class="card" data-task="'+t.id+'"><div class="card-title">'+esc(t.title)+' <i class="dot '+t.category+'"></i></div><div class="tags">'+(t.tags||[]).slice(0,3).map(x=>'<span class="tag">#'+esc(x)+'</span>').join("")+'</div><div class="card-bottom"><span class="'+(late?"late":"")+'">'+(due?"◷ "+due:"")+'</span><span>'+(n?"▢ "+n:"")+'</span></div></button>'}
function openTask(id,status){current=id?tasks.find(x=>x.id===id):null;$("#dialog-title").textContent=current?"Карточка задачи":"Новая задача";$("#task-title").value=current?.title||"";$("#task-description").value=current?.description||"";$("#task-status").value=current?.status||status||"inbox";$("#task-category").value=current?.category||"work";$("#task-due").value=current?.due_date||"";$("#task-tags").value=(current?.tags||[]).join(", ");$("#activity").hidden=!current;$("#delete-task").hidden=!current;$("#comments").innerHTML=current?(comments.filter(x=>x.task_id===current.id).map(x=>'<div class="comment">'+esc(x.body)+'<time>'+fmt(x.created_at)+'</time></div>').join("")||"<p class='muted'>Пока нет комментариев.</p>"):"";$("#task-dialog").showModal()}
$("#task-form").onsubmit=async e=>{e.preventDefault();let x={title:$("#task-title").value.trim(),description:$("#task-description").value.trim(),status:$("#task-status").value,category:$("#task-category").value,due_date:$("#task-due").value||null,tags:$("#task-tags").value.split(",").map(x=>x.trim().replace(/^#/,"")).filter(Boolean),updated_at:new Date().toISOString()};if(!x.title||!user)return;let r=current?db.from("tasks").update(x).eq("id",current.id):db.from("tasks").insert({...x,user_id:user.id});if((await r).error)return alert("Не удалось сохранить задачу.");$("#task-dialog").close();load()};
$("#add-comment").onclick=async()=>{let body=$("#comment-input").value.trim();if(!body||!current||!user)return;if((await db.from("task_comments").insert({task_id:current.id,body,user_id:user.id})).error)return alert("Не удалось добавить комментарий.");await db.from("tasks").update({updated_at:new Date().toISOString()}).eq("id",current.id);$("#comment-input").value="";await load();openTask(current.id)};
$("#delete-task").onclick=async()=>{if(current&&confirm("Удалить задачу вместе с комментариями?")){await db.from("tasks").delete().eq("id",current.id);$("#task-dialog").close();load()}};
$("#new-task").onclick=()=>openTask();$("#search").oninput=render;$("#category-filter").onchange=render;$("#status-filter").onchange=render;
$("#export").onclick=()=>{let rows=tasks.filter(t=>t.status==="done").map(t=>[t.title,{work:"Работа",personal:"Личное",home:"Дом"}[t.category],t.due_date||"",comments.filter(c=>c.task_id===t.id).map(c=>fmt(c.created_at)+" — "+c.body).join(" | ")]),csv=["Задача;Категория;Дедлайн;Комментарии"].concat(rows.map(r=>r.map(x=>'"'+String(x).replaceAll('"','""')+'"').join(";"))).join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}));a.download="выполненные-задачи.csv";a.click()};
$("#auth-switch").onclick=()=>{registerMode=!registerMode;setAuthMode()};
$("#auth-form").onsubmit=async e=>{e.preventDefault();let email=$("#auth-email").value.trim(),password=$("#auth-password").value;if(!email||!password)return;$("#auth-submit").disabled=true;authNotice("");let result=registerMode?await db.auth.signUp({email,password,options:{emailRedirectTo:location.origin+location.pathname}}):await db.auth.signInWithPassword({email,password});$("#auth-submit").disabled=false;if(result.error)return authNotice(result.error.message,true);if(registerMode&&!result.data.session)return authNotice("Проверьте почту: мы отправили ссылку для подтверждения регистрации.");if(result.data.session?.user)return showApp(result.data.session.user);if(registerMode)return authNotice("Учётная запись создана. Выполняем вход…");};
$("#logout").onclick=()=>db.auth.signOut();
db.auth.onAuthStateChange((_event,session)=>showApp(session?.user));
db.auth.getSession().then(({data})=>{if(!user)showApp(data.session?.user)});
setAuthMode();
